# Geographic Analysis

## Objective

Analyze recovery performance across different accident locations to identify regions with the highest financial exposure, collection efficiency, and operational opportunities.

### Business Questions

- Which locations have the highest number of claims?
- Which locations contribute the highest recovery amount?
- Which locations have the highest outstanding balance?
- Which locations collect money most efficiently?
- Which locations require management attention?

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
from src.preprocessing import prepare_data

pd.set_option("display.max_columns", None)

In [2]:
df= prepare_data()

In [3]:
location_summary = (
    df.groupby("Location")
      .agg(
          Claims=("Claim ID", "count"),
          Recovery=("Recovery Amount", "sum"),
          Collected=("Collected Amount", "sum"),
          Remaining=("Remaining Amount", "sum")
      )
      .reset_index()
)

location_summary["Collection Rate"] = (
    location_summary["Collected"] /
    location_summary["Recovery"] * 100
).round(2)

location_summary["Avg Recovery per Claim"] = (
    location_summary["Recovery"] /
    location_summary["Claims"]
).round(2)

location_summary.sort_values(
    "Recovery",
    ascending=False,
    inplace=True
)

location_summary.head(10)

,Location,Claims,Recovery,Collected,Remaining,Collection Rate,Avg Recovery per Claim
48,Riyadh,1353,13350874.89,878966.98,12471905.06,6.58,9867.61
39,Jeddah,716,8492298.97,124739.94,8367554.98,1.47,11860.75
24,Al-Makkah Muakarrama,278,3506824.99,31233.05,3475591.94,0.89,12614.48
17,Al Ta'if,86,1317102.56,14349.77,1302752.29,1.09,15315.15
23,Al-Madinah Munawarah,90,792666.73,30570.45,762096.28,3.86,8807.41
8,Al Dammam,78,621290.06,49445.85,571843.86,7.96,7965.26
52,Tabuk,53,611829.58,0.00,611829.58,0.00,11543.95
2,Abha,39,528059.02,737.00,527322.02,0.14,13539.97
21,Al-Kharj,34,512193.77,57578.14,454615.63,11.24,15064.52
36,Hail,52,446782.15,17653.60,429127.56,3.95,8591.96

### Q1) Which locations generate the highest number of claims?

In [4]:
fig = px.bar(
    location_summary.sort_values("Claims").tail(10),
    x="Claims",
    y="Location",
    orientation="h",
    color="Claims",
    text_auto=".2s",
    title="Claims by Accident Location"
)

fig.show()

### Insight
This visualization identifies accident hotspots and regions contributing the highest operational workload.

### Q2) Which locations have the highest recovery portfolio?

In [5]:
fig = px.bar(
    location_summary.sort_values("Recovery").tail(10),
    x="Recovery",
    y="Location",
    orientation="h",
    color="Recovery",
    text_auto=".2s",
    title="Recovery by Accident Location"
)

fig.show()

### Insight
Locations with the highest recovery amounts represent the largest financial exposure and should receive additional monitoring.

### Q3) Which locations have the highest outstanding balance?

In [6]:
fig = px.bar(
    location_summary.sort_values("Remaining").tail(10),
    x="Remaining",
    y="Location",
    orientation="h",
    color="Remaining",
    text_auto=".2s",
    title="Outstanding Recovery by Location"
)

fig.show()

### Insight
High outstanding balances indicate locations where recovery efforts should be prioritized.

### Q4) Which locations recover money most efficiently?

In [7]:
fig = px.bar(
    location_summary.sort_values("Collection Rate").tail(10),
    x="Collection Rate",
    y="Location",
    orientation="h",
    color="Collection Rate",
    text="Collection Rate",
    title="Collection Rate by Location (%)",
    color_continuous_scale="Viridis"
)

fig.show()

### Insight
Collection Rate normalizes performance across locations and highlights regions with the most effective recovery process.

### Q5) Average Recovery per Claim

In [8]:
fig = px.bar(
    location_summary.sort_values("Avg Recovery per Claim").tail(10),
    x="Avg Recovery per Claim",
    y="Location",
    orientation="h",
    color="Avg Recovery per Claim",
    text_auto=".2s",
    title="Average Recovery Amount per Claim"
)

fig.show()

### Insight
This metric highlights locations where individual claims tend to be financially larger, helping distinguish claim volume from claim severity.

### Geographic Scorecard

In [9]:
scorecard = location_summary[
    [
        "Location",
        "Claims",
        "Recovery",
        "Collected",
        "Remaining",
        "Collection Rate",
        "Avg Recovery per Claim"
    ]
].head(10)

scorecard

,Location,Claims,Recovery,Collected,Remaining,Collection Rate,Avg Recovery per Claim
48,Riyadh,1353,13350874.89,878966.98,12471905.06,6.58,9867.61
39,Jeddah,716,8492298.97,124739.94,8367554.98,1.47,11860.75
24,Al-Makkah Muakarrama,278,3506824.99,31233.05,3475591.94,0.89,12614.48
17,Al Ta'if,86,1317102.56,14349.77,1302752.29,1.09,15315.15
23,Al-Madinah Munawarah,90,792666.73,30570.45,762096.28,3.86,8807.41
8,Al Dammam,78,621290.06,49445.85,571843.86,7.96,7965.26
52,Tabuk,53,611829.58,0.00,611829.58,0.00,11543.95
2,Abha,39,528059.02,737.00,527322.02,0.14,13539.97
21,Al-Kharj,34,512193.77,57578.14,454615.63,11.24,15064.52
36,Hail,52,446782.15,17653.60,429127.56,3.95,8591.96

### Executive Insights

In [10]:
top_claims = location_summary.loc[
    location_summary["Claims"].idxmax()
]

top_recovery = location_summary.loc[
    location_summary["Recovery"].idxmax()
]

top_collection = location_summary.loc[
    location_summary["Collection Rate"].idxmax()
]

top_remaining = location_summary.loc[
    location_summary["Remaining"].idxmax()
]

print(f"""
📍 EXECUTIVE GEOGRAPHIC INSIGHTS

• Highest Claim Volume:
  {top_claims['Location']} ({top_claims['Claims']} claims)

• Largest Recovery Portfolio:
  {top_recovery['Location']}
  SAR {top_recovery['Recovery']:,.0f}

• Highest Collection Efficiency:
  {top_collection['Location']}
  ({top_collection['Collection Rate']:.2f}%)

• Largest Outstanding Balance:
  {top_remaining['Location']}
  SAR {top_remaining['Remaining']:,.0f}
""")

📍 EXECUTIVE GEOGRAPHIC INSIGHTS

• Highest Claim Volume:
  Riyadh (1353 claims)

• Largest Recovery Portfolio:
  Riyadh
  SAR 13,350,875

• Highest Collection Efficiency:
  المجاردة
  (54.55%)

• Largest Outstanding Balance:
  Riyadh
  SAR 12,471,905

### Locations by Bussiness Priority

In [11]:
conditions = [
    location_summary["Collection Rate"] >= 70,
    location_summary["Collection Rate"].between(40, 70),
    location_summary["Collection Rate"] < 40
]

choices = [
    "🟢 Healthy",
    "🟡 Monitor",
    "🔴 Critical"
]

location_summary["Priority"] = np.select(
    conditions,
    choices,
    default="Unknown"
)

location_summary[
    [
        "Location",
        "Collection Rate",
        "Priority"
    ]
].sort_values("Collection Rate").sample(10) #run it multiple times to see different samples

                Location  Collection Rate    Priority
48                Riyadh             6.58  🔴 Critical
15          Al Qunfudhah             0.00  🔴 Critical
24  Al-Makkah Muakarrama             0.89  🔴 Critical
8              Al Dammam             7.96  🔴 Critical
20           Al-Khamasin             0.00  🔴 Critical
59      Yanbu Al-Nakheel             0.00  🔴 Critical
66                النماص             0.00  🔴 Critical
62              العزيزية             0.00  🔴 Critical
44               Muhayil             0.00  🔴 Critical
57       Wadei Al-Dwaser             0.00  🔴 Critical

In [12]:
fig = px.scatter(
    location_summary,
    x="Recovery",
    y="Collection Rate",
    size="Claims",
    color="Remaining",
    hover_name="Location",
    title="Location Performance Matrix",
    labels={
        "Recovery": "Recovery Amount",
        "Collection Rate": "Collection Rate (%)"
    }
)

fig.show()

### Business Value
#### This single chart answers:
- Which locations have large recovery portfolios?
- Which have poor collection rates?
- Which handle the most claims?
- Which have the largest remaining balance?

# Conclusion

Key findings from the geographic analysis include:

- Recovery performance varies significantly across locations.
- Several locations contribute disproportionately to the overall recovery portfolio.
- Collection efficiency differs across regions, indicating opportunities for process improvement.
- A small number of locations account for a large share of outstanding balances.
- The standardized location mapping successfully resolved inconsistencies caused by multilingual names, spelling variations, and formatting differences, ensuring reliable geographic reporting.

These findings will be incorporated into the interactive Streamlit dashboard to support executive decision-making.